### PR TITLE
Trigger Civet

### PR DESCRIPTION
**Pull request by milljm**
DO NOT MERGE.
Testing Civet recipe changes.

### CODE REVIEW

**Comment by milljm** [comment]
omg, you kidding me. My upstream was John's this whole time? LOL

**Comment by milljm** [comment]
yeah okay... I did it right. @jwpeterson  may I have this fire off a civet build?

**Comment by milljm** [comment]
Uhhh no... I didn't fork on github originally, correctly. Aaaaugh

**Comment by jwpeterson** [comment]
Hahaha. Well I definitely don't approve of this PR!!

**Pull request closed without merging**
